------------------------------------------------------------------
-- mai4610_mai4700_ddl_upg.sql
------------------------------------------------------------------


------------------------------------------------------------------

--
--   PVCS Identifiers :-
--
--       PVCS id          : $Header:   //vm_latest/archives/mai/install/mai4610_mai4700_ddl_upg.sql-arc   1.0   Dec 16 2013 08:46:20   Chris.Baugh  $
--       Module Name      : $Workfile:   mai4610_mai4700_ddl_upg.sql  $
--       Date into PVCS   : $Date:   Dec 16 2013 08:46:20  $
--       Date fetched Out : $Modtime:   Oct 24 2013 10:03:04  $
--       Version          : $Revision:   1.0  $
--
------------------------------------------------------------------
--	Copyright (c) exor corporation ltd, 2013

SET ECHO OFF
SET LINESIZE 120
SET HEADING OFF
SET FEEDBACK OFF
------------------------------------------------------------------


------------------------------------------------------------------
SET TERM ON
PROMPT INV_TYPE_TRANSLATION changes for UKP
SET TERM OFF

------------------------------------------------------------------
-- 
-- DEVELOPMENT COMMENTS (CHRIS BAUGH)
-- Addition columns added for Inventory loader
-- 
------------------------------------------------------------------
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS76 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS77 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS78 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS79 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS80 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS81 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS82 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS83 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS84 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS85 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS86 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS87 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS88 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS89 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS90 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS91 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS92 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS93 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS94 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS95 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS96 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS97 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS98 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS99 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS100 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS101 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS102 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS103 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS104 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS105 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS106 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS107 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS108 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS109 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS110 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS111 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS112 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS113 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS114 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS115 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS116 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS117 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS118 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS119 VARCHAR2(32);
--
ALTER TABLE INV_TYPE_TRANSLATIONS ADD ITY_HHPOS120 VARCHAR2(32);
--
------------------------------------------------------------------



------------------------------------------------------------------
-- end of script 
------------------------------------------------------------------

