SET LINESIZE 200
--  
--  Make backup copy of original table 
ALTER TABLE DEF_TYPES RENAME TO DEF_TYPES_X ; 

CREATE TABLE DEF_TYPES
 (DTY_ATV_ACTY_AREA_CODE VARCHAR2(2) NOT NULL
 ,DTY_DEFECT_CODE VARCHAR2(4) NOT NULL
 ,DTY_DTP_FLAG VARCHAR2(1) NOT NULL
 ,DTY_DESCR1 VARCHAR2(40)
 ,DTY_DESCR2 VARCHAR2(40)
 ,DTY_HH_ATTRIBUTE_1 VARCHAR2(32)
 ,DTY_HH_ATTRIBUTE_2 VARCHAR2(32)
 ,DTY_HH_ATTRIBUTE_3 VARCHAR2(32)
 ,DTY_HH_ATTRIBUTE_4 VARCHAR2(32)
 ,DTY_HH_ATTRI_TEXT_1 VARCHAR2(12)
 ,DTY_HH_ATTRI_TEXT_2 VARCHAR2(12)
 ,DTY_HH_ATTRI_TEXT_3 VARCHAR2(12)
 ,DTY_HH_ATTRI_TEXT_4 VARCHAR2(12)
 ,DTY_START_DATE DATE
 ,DTY_END_DATE DATE
 )
/

--  Copy the data from the renamed table  
DECLARE 
 INSERT_COUNT NUMBER := 1;
 CURSOR c1 IS SELECT * from DEF_TYPES_X SEL_TBL;
BEGIN
  FOR r1 IN c1 LOOP
    INSERT INTO DEF_TYPES INS_TBL
     (DTY_ATV_ACTY_AREA_CODE
     ,DTY_DEFECT_CODE
     ,DTY_DTP_FLAG
     ,DTY_DESCR1
     ,DTY_DESCR2
     ,DTY_HH_ATTRIBUTE_1
     ,DTY_HH_ATTRIBUTE_2
     ,DTY_HH_ATTRIBUTE_3
     ,DTY_HH_ATTRIBUTE_4
     ,DTY_HH_ATTRI_TEXT_1
     ,DTY_HH_ATTRI_TEXT_2
     ,DTY_HH_ATTRI_TEXT_3
     ,DTY_HH_ATTRI_TEXT_4
     ,DTY_START_DATE
     ,DTY_END_DATE)
    VALUES 
    (r1.DTY_ATV_ACTY_AREA_CODE
    ,r1.DTY_DEFECT_CODE
    ,r1.DTY_DTP_FLAG
    ,r1.DTY_DESCR1
    ,r1.DTY_DESCR2
    ,r1.DTY_HH_ATTRIBUTE_1
    ,r1.DTY_HH_ATTRIBUTE_2
    ,r1.DTY_HH_ATTRIBUTE_3
    ,r1.DTY_HH_ATTRIBUTE_4
    ,r1.DTY_HH_ATTRI_TEXT_1
    ,r1.DTY_HH_ATTRI_TEXT_2
    ,r1.DTY_HH_ATTRI_TEXT_3
    ,r1.DTY_HH_ATTRI_TEXT_4
    ,r1.DTY_START_DATE
    ,r1.DTY_END_DATE); 
  END LOOP;
COMMIT;
END ; 
  
/
 
Commit ; 
  
 
-- Drop all other user named indexes 
DROP INDEX DTY_INDEX_P1;
 
 
--  Recreate Indexes, Constraints, and Grants 
CREATE UNIQUE INDEX DTY_INDEX_P1 ON DEF_TYPES
(DTY_DEFECT_CODE, DTY_ATV_ACTY_AREA_CODE, DTY_DTP_FLAG)
 
--  There are no foriegn key constraints that reference the new table to recreate. 
 
--  Analyze New Table 
Analyze Table DORSET.DEF_TYPES Compute Statistics;
 
--  Recompile any dependent objects 
 